### ISSUE TITLE
There is a problem in model training

### ISSUE THREAD

**Issue by zp19990818** [suhwan-cho/TMO#10]
Hi, 

my dataset is binary segment data and has been modified in util.py. It can be trained, and the loss shows that it is going down. But the output iou has not been quite normal. I have two datasets; one has stabilized at 1 in less than 20 rounds of iou, and the other iou has been 0. Has the initialization of the model created any problems?

![0e71deccdec56e7715d25fef833a180](https://github.com/suhwan-cho/TMO/assets/53686038/e7669bd7-306a-42dd-bc6d-d608b9e7cc5c)

![9af1b704ad42a3eea2b49eb9ae630ce](https://github.com/suhwan-cho/TMO/assets/53686038/70837af1-e7df-4553-8b15-046580b4af7e)

**Comment by suhwan-cho** [comment]
Hi,

Is training going well with the original datasets?

**Comment by zp19990818** [comment]
> Hi,
> 
> Is training going well with the original datasets?

Yes, they train normally on the original dataset. But my data is also normal and runnable, I think it might be the dataset distribution as well as the network initialization. I'll go ahead and debug it myself, thanks for your advice!

**Comment by suhwan-cho** [comment]
Great, no worries!

**Comment by zp19990818** [comment]
> Great, no worries!

I saw your suggestion in another discussion (https://github.com/suhwan-cho/TMO/issues/7) and tried to modify the object pixel values from [255,255,255] to [128,0,0]. It takes a while to wait, but the training works. Thanks for the suggestion, but I think there may indeed be some problem here, but I can't locate it.

Anyway, thanks again!
