### ISSUE TITLE
some questions about output selection

### ISSUE THREAD

**Issue by zp19990818** [suhwan-cho/TMO#11]
Hello, 

I'm coming back to this. I have two questions about output selection:

1. I trained as well as tested on the new TMO without using output selection and the metrics show up the same as the previous version of TMO, but the visualized binary map has significant edge jaggedness. I'm curious as to why the visualization results differ, but I'm calculating the same metrics. The presence of edge jaggedness should be lower for miou. The new TMO predicted binary plot is below. (Is it because of parameter B? Is the output soft score?) 
![7398_00021](https://github.com/suhwan-cho/TMO/assets/53686038/1ab876b1-6ad1-492a-8382-4e4b84d0dc8d)
![image](https://github.com/suhwan-cho/TMO/assets/53686038/7e32f65a-1d65-470b-a366-92258ab5d77a)

2. On my own dataset, performance drops significantly using output selection. I looked at the code and the purpose of output selection seems to be to compare the percentage of more defined pixels in the saliency map (non-blurred areas). Is this somewhat inappropriate for confidence calculations? For example, structural similarity is not taken into account. The parameter B, here, is meant to be binary, so should the output selection be done when calculating the final score?

Looking forward to your reply~

**Comment by suhwan-cho** [comment]
Hi,

1. TMO handles each video frame after converting it to 384p resolution and resize the output back to the original resolution. If you want to preserve sharp edges, you can just skip the resizing processes.

2. B indicates the batch size. It is used to identify if TMO is in the training mode or in the testing mode. The threshold value for adaptive output selection is defined as h.

**Comment by zp19990818** [comment]
> Hi,
> 
> 1. TMO handles each video frame after converting it to 384p resolution and resize the output back to the original resolution. If you want to preserve sharp edges, you can just skip the resizing processes.
> 2. B indicates the batch size. It is used to identify if TMO is in the training mode or in the testing mode. The threshold value for adaptive output selection is defined as h.

Thank you, I got it!
