### ISSUE TITLE
Question about new backbone encoder

### ISSUE THREAD

**Issue by JawadTawhidi** [suhwan-cho/TMO#12]
Hi, as much as I knew about your code you were just using ResNet101 as backbone encoder, but now I can see you have added another backbone encoder, I just want to ask that the result of TMO using these 2 backbone encoder is same or the result will be changed if we use the new one? 

One more question, as I am totally new in this area, I want to know how TMO encoder deals with temporal information? according to your former code, the TMO was completely ignoring temporal information and was just extracting features from of images/frames.

**Comment by suhwan-cho** [comment]
Hi,

The code has been modified a little according to our extended work (TMO++).

**Comment by JawadTawhidi** [comment]
Hi, Ok. Does TMO++ increase the results? or only it provides another option for backbone encoder?

**Comment by suhwan-cho** [comment]
There was some improvements. 
Please check the paper in the README file.
