### ISSUE TITLE
Question about evaluation using new data set

### ISSUE THREAD

**Issue by JawadTawhidi** [suhwan-cho/TMO#13]
Hi, I want to use TMO for new data set. My data set is such that in some videos it has single object, but it also has multiple objects in some videos. In this case can I use the code of " if mode == 'val'" in trainer.py file to calculate F and J for my dataset?

**Comment by suhwan-cho** [comment]
Hi,

It depends on how you defined the target objects.
If multiple objects are identically annotated with 1, you can directly use the validation code.

**Comment by JawadTawhidi** [comment]
Hi again, 

Sorry for asking so much questions, I am new in this area, would you please give more clue?

1. You mean to use validation code directly the pixel values of a frame should be 0 and 1, such that 0 must represent all the non objects area(Background) and 1 must represent all the objects(Multiple objects in my case)?
2. My data set is been normalized by dividing each pixel by 255.0, is this format ok for using validation code directly?
3. My last question is about the TMO's decoder, according to current structure of TMO, its encoder is only extracting appearance information and short term temporal information, after feature extraction sum of these 2 are given to decoder to generate object mask. I want to know if we change the decoder to consider long term temporal information also, in that case do we need to change decoder also or the decoder has that capability to consider these new features with old features?



I would appreciate your patience and response.
