### ISSUE TITLE
flow maps

### ISSUE THREAD

**Issue by karchen-geng** [suhwan-cho/TMO#14]
您好,我想问一下，您每个数据集的光流生成是否有具体的脚本文件？

**Comment by suhwan-cho** [comment]
Hi, please understand that I used a translator as I don't speak Chinese.

As mentioned in "Preparation", we used official RAFT model (trained on Sintel) for optical flow estimation. 
We do not provide flow generation files, but pre-processed flow files can be downloaded from my Google Drive.

**Comment by karchen-geng** [comment]
I see, thank you very much for your reply

**Comment by karchen-geng** [comment]
Hello, I'm sorry to bother you.
For the test results obtained from FBMS dataset and YouTubeObjects dataset, I have organized them in a relevant way and calculated the relevant metrics J(mean) and F(mean) in a way similar to davis2016. How did you evaluate the performance regarding these two datasets?

**Comment by suhwan-cho** [comment]
Hi, evaluation for the datasets except for DAVIS is performed in TMO code, i.e., run.py file.

**Comment by karchen-geng** [comment]
Hello, do you mean that the iou results output by run.py are the results in your paper?

**Comment by suhwan-cho** [comment]
Yes, J metric equals to IoU metric.

**Comment by karchen-geng** [comment]
Thank you again!

**Comment by suhwan-cho** [comment]
No problem!
