### ISSUE TITLE
Generating single channel output

### ISSUE THREAD

**Issue by JawadTawhidi** [suhwan-cho/TMO#15]
Hi, is it possible to generate single channel output by TMO? as TMO currently uses standard cross entropy loss, you are generating 2 channel output, can we just change the last layer of TMO to generate single channel output? if so, then do we need to change the code of IOU after loss and also the code for J and F values inside mode=val ?

**Comment by suhwan-cho** [comment]
Hi,

TMO outputs 2-channel scores during training, and those scores are converted to 1-channel output using an argmax operation during testing.

**Comment by JawadTawhidi** [comment]
Thank you so much for your response.
TMO is using standard cross entropy loss which accepts 2-channel scores, but I want to try TMO with binary cross entropy loss which expects single channel inputs. In that case can I just leave TMO as it is to generate 2-channel output, but before passing predicted scores to binary cross entropy loss change them to 1-channel output? similar the approach you have used for testing.

**Comment by suhwan-cho** [comment]
Yes, exactly!
