### ISSUE TITLE
Inference time

### ISSUE THREAD

**Issue by LingyiHongfd** [suhwan-cho/TMO#4]
Thanks for your interesting work. I want to query about the inference time. I run your codes on my 2080ti, and the environment is the same. But the inference time is just about 20 FPS,  which is the result of your print code. The FPS is quite lower than the 43.2 FPS claimed in your paper. Could you provide more details about inference or give some insight on the inference time difference?

**Comment by LingyiHongfd** [comment]
Besides, I also run the same official code on 3090. The fps is just about 30. Could you provide more details about inference?

**Comment by suhwan-cho** [comment]
Hi Lingyi, 

I have just checked the inference speed several times and consistently obtained 40+ fps on a single 2080 Ti GPU. 
Is your inference implemented without other jobs running and with the maximum GPU power (280W for 2080 Ti)?

**Comment by LingyiHongfd** [comment]
Thanks for your reply. I have checked the power and run experiments on several servers with 2080ti again. There is no other job running on the GPU, and the GPU power is 280W too. The speed is still about 20 FPS on one 2080ti. Perhaps this speed does vary somewhat from machine to machine. But I think TMO is solid and the network structure is very simple. I believe that it maybe actually achieve 40 FPS on a 2080ti. Thanks a lot.

**Comment by suhwan-cho** [comment]
No problem!
