### ISSUE TITLE
question about evaluation results

### ISSUE THREAD

**Issue by JawadTawhidi** [suhwan-cho/TMO#6]
Sorry for disturbing you again, as I mentioned in my previous issue I am new in the area of VOS. so that there are still some points which are confusing me:
 
1. I implemented your pretrained model using FBMS and Youtube_object datasets, but the 'iou's which I am getting after implementation are in different format compare to paper, for example for FBMS paper specified 79.9 as final iou, but I am getting it as 0.79980. Is it a problem? What is the difference? 
2. I want to evaluate the pretrained model on DAVIS 2016, but I could not find the official evluation code, any help for this issue? 
3. If I want to test the model on my own dataset, do I need to write separate code for finding the values of J and F?

**Comment by suhwan-cho** [comment]
Hi, sorry for the late reply.

1. I don't think that's a problem.
2. You can refer to the official evaluation code (https://github.com/davisvideochallenge/davis). 
3. J and F score calculation can be found at official DAVIS evaluation code.

**Comment by JawadTawhidi** [comment]
Thank you so mcuh for your response, but I solved those problesm, now I am facing another problem: I generated optical flow using RAFT pretrained on Sintel dataset , then I used the generated optical flows for training TMO, followed your instructions, but I am not getting good results, I know it is because of optical flows which I have generated using RAFT pretrained model, specially optical flow of the last frame(According paper when i is the last frame, i-1 is considered as target frame, I did the same thing, but not getting good resulsts) would you do one more favor and share that part of the code which you used while generating optical flow of last frame? how did you change the for loop to generate optical flow of last frame? 


I know, these questions are very basic, but for me as a beginner solving them are really big deal. I am looking forward for your reply.

**Comment by suhwan-cho** [comment]
Unfortunately, I have deleted that code.

RAFT takes two images as its input. As I remember, the first input is the target frame and the second input is the source frame.
When dealing with the last frame, you only need to use the target frame as the second input and the source frame as the first input.

**Comment by JawadTawhidi** [comment]
RAFT is taking 2 consecutive frames each time, for example if we have 5 frames, it takes like this:

frame 1 starting frame and frame 2 target frame
frame 2 starting frame and frame 3 target frame
frame 3 starting frame and frame 4 target frame
frame 4 starting frame and frame 5 target frame

But it is not generating optical flow for frame 5, because there is no any frame after it. I tried to solve this such that when it arrives to frame 5, it should take frame 5 as starting frame and frame 4 as target frame, but I did not get good results.

**Comment by JawadTawhidi** [comment]
When I used your preprocessed data for training TMO, I got better results compare to paper, for example I got 72.07 for youtube objects dataset and 80.9 for FBS while getting almost same results for DAVIS。

But when I estimated optical flow for DAVIS using RAFT pretrained model and used that data instead of your preprocessed data, I did not get good results, for example, I got 70.2 for youtube objects dataset and 79.9 for FBMS. For DAVIS I got 85.3 J value and 86.3 F value.
