### ISSUE TITLE
Question related testing TMO using new dataset

### ISSUE THREAD

**Issue by JawadTawhidi** [suhwan-cho/TMO#7]
Hi, sorry for disturbing you again and again. I wanted to ask you that if I want to test the performance of TMO model on new dataset(For example ultrasound videos) do I need to write new test code for it or I can use the codes of test_davis, test_fbms or test_ytobj? I am really confused about it, because format of ultrasound videos are different from real world videos. 

I would be really grateful if you give me some instructions or clues about it.

**Comment by JawadTawhidi** [comment]
Please, can I use code of " if mode == 'val'" in trainer.py file to calculate F and J for new dataset? even can I use this code for evaluating TMO on DAVIS 2016?(I know how to evaluate TMO on DAVIS 2016 using its official code, but I want to know what about using code of  if mode == 'val' in trainer.py )

**Comment by JawadTawhidi** [comment]
I am really sorry for disturbing you so much, the reason is that I really found TMO interesting so that I want to use it for Ultrasound videos. 

1. In my ultrasound dataset the annotations are normalized by dividing by 255, so I am thinking if I do not change the annotations to original format, will the test_davis work properly while inferring? I mean if I simply put my ultrasound dataset instead of DAVIS(Making the same directories), will the code of preprocessing dataset, the code of evaluating model and the code of if mode == 'val' in trainer.py work properly or I must change the annotations back to original format(The pixel values should be between 0 and 255 instead of being between 0 and 1)
2. One confusing thing is that, I tested the code of if mode == 'val' in trainer.py for calculating J and F values, the result is a bit different compare to the DAVIS 2016 official code. For example when I check my results on DAVIS 2016 official code, the J values is 85.6, but when I test the same results using code of if mode == 'val' in trainer.py, the J value is 85.5.(The difference is very small).


I will be very happy to hear about this issue from you.

**Comment by JawadTawhidi** [comment]
Thank you so much for responding,

 You mean I should make the background pixels [0,0,0] and the foreground pixels value [128,0,0] for annotations only, right?

**Comment by suhwan-cho** [comment]
Yes, just make sure that the annotations have the pixel values of either [0,0,0] or [128,0,0]. 
I recommend you to check the pixel values and modify them if needed. 
I cannot tell if it works because I didn't see your data.

**Comment by JawadTawhidi** [comment]
How can I check what are the annotations pixel values? even I tried to find what are the annotations pixel values of DAVIS 2016, I could not find a trusted method.

**Comment by suhwan-cho** [comment]
Hi, you can check the pixel values by converting PIL images to tensor format.

**Comment by JawadTawhidi** [comment]
I converted the PIL images to numpy array and checked the pixel values, is it correct?
