### ISSUE TITLE
Question about using optical flow while inference

### ISSUE THREAD

**Issue by JawadTawhidi** [suhwan-cho/TMO#8]
Hi, sorry for disturbing again. I wanted to say that when I am using optical flow while implementing TMO I am getting the same results as paper, but when I don't use optical flow while inference, I am getting lower results.(I am implementing your pretrained model and I am setting flow path to JPEGImages instead of JPEGFlows)

I am asking this question because paper says that TMO can run with and without optical flow.

I just want to know that when you run TMO with and without optical flow, are you getting the same results? or the results of using optical flow is higher than the results of not using it?

**Comment by suhwan-cho** [comment]
Hi, TMO can handle both RGB images and optical flow maps as motion input, but the accuracies are different.
The optimal source information varies by the target dataset (check Table 3 in the paper).
