### ISSUE TITLE
Looks like some files are missing

### ISSUE THREAD

**Issue by zp19990818** [suhwan-cho/TMO#9]
Hi, 

I'm glad you updated the repository again, but some files seem to be missing. I want to use mit-b1 as the backbone, just like the one in tmo.py, but I can't find the Segformer model, is it convenient for you to provide a copy?

![image](https://github.com/suhwan-cho/TMO/assets/53686038/63b1a9cf-673b-4917-8850-0b939ccab4a9)

**Comment by suhwan-cho** [comment]
Hi,
 
SegformerModel can be found at "transformers" package.
Please install all the packages in requirements file.

Thanks!

**Comment by zp19990818** [comment]
> Hi,
> 
> SegformerModel can be found at "transformers" package. Please install all the packages in requirements file.
> 
> Thanks!

Got it！Thank you.
